### 聚合操作

In [3]:
import numpy as np
L = np.random.rand(100)
L

array([0.08438316, 0.21395043, 0.76946522, 0.69434504, 0.39957271,
       0.39539881, 0.38881937, 0.36256667, 0.53237442, 0.28157651,
       0.39029427, 0.20786674, 0.51270916, 0.79949901, 0.8872649 ,
       0.36026013, 0.12446831, 0.70591388, 0.99753567, 0.79641678,
       0.01760393, 0.47558317, 0.5308387 , 0.63862025, 0.27631488,
       0.41643071, 0.79745659, 0.04321217, 0.35218084, 0.79966338,
       0.17978988, 0.59074408, 0.94682043, 0.50514314, 0.62897821,
       0.73231891, 0.61758925, 0.86791009, 0.28598814, 0.71165313,
       0.84184566, 0.22467995, 0.36562414, 0.13135467, 0.25104911,
       0.80262612, 0.70974437, 0.0750337 , 0.27209587, 0.39999579,
       0.11063955, 0.16975979, 0.01556629, 0.9097893 , 0.33696946,
       0.93355745, 0.98545232, 0.64450757, 0.64158253, 0.07206224,
       0.16239293, 0.91892581, 0.38572254, 0.73589473, 0.05022331,
       0.89148491, 0.48582185, 0.26515605, 0.0566247 , 0.52053402,
       0.41001344, 0.23754037, 0.91851998, 0.36499808, 0.48514

In [4]:
sum(L)

49.62550927793868

In [5]:
np.sum(L)

49.6255092779387

In [6]:
big_array = np.random.rand(100000)
%timeit sum(big_array)
%timeit np.sum(big_array)

14.4 ms ± 174 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
29.9 µs ± 641 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [7]:
np.min(big_array)

7.358263601431325e-06

In [8]:
np.max(big_array)

0.9999864591582245

In [10]:
big_array.max()  # np.max()

0.9999864591582245

In [13]:
X = np.arange(16).reshape((4, -1))
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [12]:
np.sum(X)

120

In [14]:
np.sum(X, axis=0)  # 每一列的和。 沿着axis进行计算。

array([24, 28, 32, 36])

In [15]:
np.sum(X, axis=1)  # 压缩axis轴

array([ 6, 22, 38, 54])

In [16]:
np.prod(X)  # product 乘积

0

In [17]:
np.prod(X+1)

20922789888000

In [18]:
np.mean(X)

7.5

In [19]:
np.median(X)

7.5

In [20]:
v = np.array([1, 2, 1, 2, 10])  # 有离群点
np.mean(v)

3.2

In [21]:
np.median(v)

2.0

In [22]:
np.percentile(big_array, q=50)  # 分位数

0.4985695618056841

In [23]:
np.median(big_array)

0.4985695618056841

In [25]:
for percent in [0, 25, 50, 75, 100]:
    print(np.percentile(big_array, q=percent))

7.358263601431325e-06
0.2512140662485084
0.4985695618056841
0.7482419258680149
0.9999864591582245


In [26]:
np.var(big_array)

0.08275343186007315

In [27]:
np.std(big_array)

0.28766896228142713

In [28]:
x = np.random.normal(0, 1, size=1000000)
x

array([-0.14260867, -0.45481328, -0.22574033, ..., -0.63466218,
        0.80153982,  0.1811991 ])

In [30]:
np.mean(x)

0.0008455661194347831

In [31]:
np.std(x)

1.0004647293469333

### 索引

In [32]:
np.min(x)

-5.3166477623700095

In [33]:
np.argmin(x)   # 最小值所在的索引

790958

In [34]:
x[790958]

-5.3166477623700095

In [35]:
np.argmax(x)

239512

In [36]:
x[239512]

5.084197892347431

In [38]:
np.max(x)

5.084197892347431

### 排序和使用索引

In [40]:
x = np.arange(16)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [41]:
np.random.shuffle(x)
x

array([11,  4,  1,  3,  0, 10, 12,  5,  7,  8,  6,  2,  9, 13, 15, 14])

In [42]:
np.sort(x) # 不改变x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [43]:
x

array([11,  4,  1,  3,  0, 10, 12,  5,  7,  8,  6,  2,  9, 13, 15, 14])

In [44]:
x.sort()   # 改变x

In [45]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [46]:
X = np.random.randint(10, size=(4,4))
X

array([[7, 6, 1, 7],
       [2, 6, 1, 2],
       [6, 3, 4, 7],
       [5, 8, 7, 3]])

In [47]:
np.sort(X)

array([[1, 6, 7, 7],
       [1, 2, 2, 6],
       [3, 4, 6, 7],
       [3, 5, 7, 8]])

In [49]:
np.sort(X, axis=1) # 默认是1，沿着列排序，每一行变有序

array([[1, 6, 7, 7],
       [1, 2, 2, 6],
       [3, 4, 6, 7],
       [3, 5, 7, 8]])

In [50]:
np.sort(X, axis=0)

array([[2, 3, 1, 2],
       [5, 6, 1, 3],
       [6, 6, 4, 7],
       [7, 8, 7, 7]])

In [51]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [53]:
np.random.shuffle(x)

In [54]:
x

array([13,  3, 12, 10,  0,  2,  4,  1,  8,  9, 11, 15, 14,  6,  7,  5])

In [55]:
np.argsort(x)  # 得到有序的索引。第一个元素为第一小值的位置

array([ 4,  7,  5,  1,  6, 15, 13, 14,  8,  9,  3, 10,  2,  0, 12, 11])

In [57]:
np.partition(x, 3)   # 快速排序 标定点。 3前面的数字比3小，3后边的数字比3大

array([ 1,  0,  2,  3,  4,  5, 10, 12,  8,  9, 11, 15, 14,  6,  7, 13])

In [58]:
np.argpartition(x, 3)

array([ 7,  4,  5,  1,  6, 15,  3,  2,  8,  9, 10, 11, 12, 13, 14,  0])

In [59]:
X

array([[5, 8, 7, 3],
       [2, 6, 1, 2],
       [7, 6, 1, 7],
       [6, 3, 4, 7]])

In [60]:
np.argsort(X, axis=1)  # 按行排序

array([[3, 0, 2, 1],
       [2, 0, 3, 1],
       [2, 1, 0, 3],
       [1, 2, 0, 3]])

In [61]:
np.argpartition(X, 2, axis=1)  

array([[3, 0, 2, 1],
       [2, 0, 3, 1],
       [2, 1, 0, 3],
       [1, 2, 0, 3]])

In [62]:
np.argpartition(X, 2, axis=0)

array([[1, 3, 1, 1],
       [0, 1, 2, 0],
       [3, 2, 3, 2],
       [2, 0, 0, 3]])