In [1]:
import numpy as np

In [2]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
X = np.arange(15).reshape(3, -1)
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

### 基本属性

In [5]:
x.ndim

1

In [6]:
X.ndim

2

In [7]:
x.shape

(10,)

In [8]:
X.shape

(3, 5)

In [9]:
x.size   # 元素个数

10

In [10]:
X.size

15

### np.array数据访问

In [11]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
x[0]

0

In [13]:
 x[-1]

9

In [14]:
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [15]:
X[0][0]  # 不建议这么写

0

In [16]:
X[(0,0)]  # 访问array中的元素

0

In [17]:
X[0, 0]  # 括号可省略

0

In [18]:
x[0:5]

array([0, 1, 2, 3, 4])

In [19]:
x[:5]

array([0, 1, 2, 3, 4])

In [21]:
x[5:]

array([5, 6, 7, 8, 9])

In [22]:
x[::2]

array([0, 2, 4, 6, 8])

In [23]:
x[::-2]

array([9, 7, 5, 3, 1])

In [24]:
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [25]:
X[:2, :3]  # 前两行的前三列

array([[0, 1, 2],
       [5, 6, 7]])

In [27]:
X[:2, ::2]

array([[0, 2, 4],
       [5, 7, 9]])

In [28]:
X[::-1, ::-1]

array([[14, 13, 12, 11, 10],
       [ 9,  8,  7,  6,  5],
       [ 4,  3,  2,  1,  0]])

In [29]:
X[0]  # 取一行

array([0, 1, 2, 3, 4])

In [30]:
X[0, :]

array([0, 1, 2, 3, 4])

In [32]:
X[0, :].ndim

1

In [31]:
X[:, 0]  # 第一列

array([ 0,  5, 10])

In [34]:
subX = X[:2, :3]
subX

array([[0, 1, 2],
       [5, 6, 7]])

In [35]:
subX[0, 0] = 100
subX

array([[100,   1,   2],
       [  5,   6,   7]])

In [36]:
X

array([[100,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14]])

### 对于numpy来说，切片是浅拷贝（只拷贝引用）；list，切片是深拷贝

In [38]:
subX = X[:2, :3].copy()   # 深拷贝
subX

array([[100,   1,   2],
       [  5,   6,   7]])

In [40]:
subX[0, 0] = 0
subX

array([[0, 1, 2],
       [5, 6, 7]])

In [41]:
X

array([[100,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14]])

### reshape改变维度

In [42]:
x.shape

(10,)

In [43]:
x.ndim

1

In [44]:
x.reshape((2, 5))  # 元组的括号可以省略

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [46]:
x.reshape(2, 5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [47]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [49]:
A = x.reshape((2, 5))
A

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [51]:
B = x.reshape(1, 10)
B

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [55]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [52]:
B.ndim

2

In [53]:
B.shape

(1, 10)

In [54]:
x.reshape(10, -1)  # 有10行


array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [56]:
x.reshape(-1, 10)

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [57]:
x.reshape(2, -1)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

### 合并操作

In [59]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])

In [60]:
x

array([1, 2, 3])

In [61]:
y

array([3, 2, 1])

In [62]:
np.concatenate([x, y])  # 传入列表

array([1, 2, 3, 3, 2, 1])

In [63]:
z = np.array([6, 7, 8])

In [64]:
np.concatenate([x, y, z])

array([1, 2, 3, 3, 2, 1, 6, 7, 8])

In [65]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])

In [66]:
np.concatenate([A, A])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [67]:
np.concatenate([A, A], axis=1) # 默认为0，第一个维度；1：第二个维度

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [68]:
np.concatenate([A, z])

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [69]:
np.concatenate([A, z.reshape(1, -1)])  # 将z加入A

array([[1, 2, 3],
       [4, 5, 6],
       [6, 7, 8]])

In [70]:
A

array([[1, 2, 3],
       [4, 5, 6]])

In [72]:
A2 = np.concatenate([A, z.reshape(1, -1)])  # 将z加入A
A2

array([[1, 2, 3],
       [4, 5, 6],
       [6, 7, 8]])

In [73]:
np.vstack([A, z])  # 即使维度不同也可以拼接

array([[1, 2, 3],
       [4, 5, 6],
       [6, 7, 8]])

In [74]:
B = np.full((2, 2), fill_value=100)
B

array([[100, 100],
       [100, 100]])

In [75]:
np.hstack([A, B])

array([[  1,   2,   3, 100, 100],
       [  4,   5,   6, 100, 100]])

### 分割操作

In [78]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [80]:
x1, x2, x3 = np.split(x, [3, 7])

In [81]:
x1

array([0, 1, 2])

In [82]:
x2

array([3, 4, 5, 6])

In [83]:
x3

array([7, 8, 9])

In [85]:
help(np.split)


Help on function split in module numpy:

split(ary, indices_or_sections, axis=0)
    Split an array into multiple sub-arrays as views into `ary`.
    
    Parameters
    ----------
    ary : ndarray
        Array to be divided into sub-arrays.
    indices_or_sections : int or 1-D array
        If `indices_or_sections` is an integer, N, the array will be divided
        into N equal arrays along `axis`.  If such a split is not possible,
        an error is raised.
    
        If `indices_or_sections` is a 1-D array of sorted integers, the entries
        indicate where along `axis` the array is split.  For example,
        ``[2, 3]`` would, for ``axis=0``, result in
    
          - ary[:2]
          - ary[2:3]
          - ary[3:]
    
        If an index exceeds the dimension of the array along `axis`,
        an empty sub-array is returned correspondingly.
    axis : int, optional
        The axis along which to split, default is 0.
    
    Returns
    -------
    sub-arrays : list 

In [87]:
A = np.arange(16).reshape((4, 4))
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [88]:
np.split(A, indices_or_sections=[2])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [89]:
A1, A2 = np.split(A, indices_or_sections=[2])

In [90]:
A3, A4 = np.split(A, indices_or_sections=[2], axis=1)

In [91]:
A3

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [94]:
upper, lower = np.vsplit(A, [2])

In [93]:
help(np.vsplit)

Help on function vsplit in module numpy:

vsplit(ary, indices_or_sections)
    Split an array into multiple sub-arrays vertically (row-wise).
    
    Please refer to the ``split`` documentation.  ``vsplit`` is equivalent
    to ``split`` with `axis=0` (default), the array is always split along the
    first axis regardless of the array dimension.
    
    See Also
    --------
    split : Split an array into multiple sub-arrays of equal size.
    
    Examples
    --------
    >>> x = np.arange(16.0).reshape(4, 4)
    >>> x
    array([[ 0.,   1.,   2.,   3.],
           [ 4.,   5.,   6.,   7.],
           [ 8.,   9.,  10.,  11.],
           [12.,  13.,  14.,  15.]])
    >>> np.vsplit(x, 2)
    [array([[0., 1., 2., 3.],
           [4., 5., 6., 7.]]), array([[ 8.,  9., 10., 11.],
           [12., 13., 14., 15.]])]
    >>> np.vsplit(x, np.array([3, 6]))
    [array([[ 0.,  1.,  2.,  3.],
           [ 4.,  5.,  6.,  7.],
           [ 8.,  9., 10., 11.]]), array([[12., 13., 14., 15.]]), arr

In [95]:
left, right = np.hsplit(A, [2])

In [96]:
data = np.arange(16).reshape((4,4))
data

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [97]:
X, y = np.hsplit(data, [-1])

In [98]:
X

array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 8,  9, 10],
       [12, 13, 14]])

In [99]:
y

array([[ 3],
       [ 7],
       [11],
       [15]])

In [100]:
y[:, 0]

array([ 3,  7, 11, 15])

### numpy.array 中的运算
给定一个向量，让向量中的每个数*2
a = [0, 2, 3]
a*2 = [0, 4, 6]

In [101]:
n = 10
L = [i for i in range(n)]

In [102]:
2 * L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [103]:
A = []
for e in L:
    A.append(2*e)
A

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [104]:
%%time
A = []
for e in L:
    A.append(2*e)
A

CPU times: user 26 µs, sys: 1 µs, total: 27 µs
Wall time: 31.7 µs


[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [105]:
%%time
A = [2*e for e in L]

CPU times: user 5 µs, sys: 0 ns, total: 5 µs
Wall time: 8.11 µs


In [111]:
L = np.arange(100)

In [115]:
%%time
A = np.array(2*e for e in L)
A

CPU times: user 29 µs, sys: 0 ns, total: 29 µs
Wall time: 34.1 µs


array(<generator object <genexpr> at 0x7f9e07fb5c50>, dtype=object)

In [113]:
%%time
A = 2 * L

CPU times: user 43 µs, sys: 104 µs, total: 147 µs
Wall time: 970 µs


In [114]:
A

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100, 102,
       104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126, 128,
       130, 132, 134, 136, 138, 140, 142, 144, 146, 148, 150, 152, 154,
       156, 158, 160, 162, 164, 166, 168, 170, 172, 174, 176, 178, 180,
       182, 184, 186, 188, 190, 192, 194, 196, 198])

In [117]:
X = np.arange(15).reshape((3, 5))
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [118]:
X + 1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [119]:
X - 1

array([[-1,  0,  1,  2,  3],
       [ 4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13]])

In [120]:
X * 2

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

In [121]:
X / 2

array([[0. , 0.5, 1. , 1.5, 2. ],
       [2.5, 3. , 3.5, 4. , 4.5],
       [5. , 5.5, 6. , 6.5, 7. ]])

In [122]:
X // 2

array([[0, 0, 1, 1, 2],
       [2, 3, 3, 4, 4],
       [5, 5, 6, 6, 7]])

In [123]:
X ** 2

array([[  0,   1,   4,   9,  16],
       [ 25,  36,  49,  64,  81],
       [100, 121, 144, 169, 196]])

In [124]:
X % 2

array([[0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0]])

In [125]:
1 / X

/Users/lin/opt/anaconda2/envs/tensorflow/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([[       inf, 1.        , 0.5       , 0.33333333, 0.25      ],
       [0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111],
       [0.1       , 0.09090909, 0.08333333, 0.07692308, 0.07142857]])

In [126]:
np.abs(X)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [127]:
np.sin(X)

array([[ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ],
       [-0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849],
       [-0.54402111, -0.99999021, -0.53657292,  0.42016704,  0.99060736]])

In [128]:
np.cos(X)

array([[ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362],
       [ 0.28366219,  0.96017029,  0.75390225, -0.14550003, -0.91113026],
       [-0.83907153,  0.0044257 ,  0.84385396,  0.90744678,  0.13673722]])

In [129]:
np.tan(X)

array([[ 0.00000000e+00,  1.55740772e+00, -2.18503986e+00,
        -1.42546543e-01,  1.15782128e+00],
       [-3.38051501e+00, -2.91006191e-01,  8.71447983e-01,
        -6.79971146e+00, -4.52315659e-01],
       [ 6.48360827e-01, -2.25950846e+02, -6.35859929e-01,
         4.63021133e-01,  7.24460662e+00]])

In [130]:
np.exp(X)

array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
        5.45981500e+01],
       [1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
        8.10308393e+03],
       [2.20264658e+04, 5.98741417e+04, 1.62754791e+05, 4.42413392e+05,
        1.20260428e+06]])

In [131]:
np.power(3, X)

array([[      1,       3,       9,      27,      81],
       [    243,     729,    2187,    6561,   19683],
       [  59049,  177147,  531441, 1594323, 4782969]])

In [132]:
np.log(X)

/Users/lin/opt/anaconda2/envs/tensorflow/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([[      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436],
       [1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458],
       [2.30258509, 2.39789527, 2.48490665, 2.56494936, 2.63905733]])

In [133]:
X + 1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [134]:
np.log2(X)

/Users/lin/opt/anaconda2/envs/tensorflow/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log2
  """Entry point for launching an IPython kernel.


array([[      -inf, 0.        , 1.        , 1.5849625 , 2.        ],
       [2.32192809, 2.5849625 , 2.80735492, 3.        , 3.169925  ],
       [3.32192809, 3.45943162, 3.5849625 , 3.70043972, 3.80735492]])

### 矩阵运算

In [135]:
A = np.arange(4).reshape((2, 2))

In [137]:
B = np.full((2, 2), fill_value=10)

In [138]:
A + B

array([[10, 11],
       [12, 13]])

In [139]:
A * B   # 对应元素做相应运算，不是矩阵乘。

array([[ 0, 10],
       [20, 30]])

In [140]:
A.dot(B)   # 矩阵乘法

array([[10, 10],
       [50, 50]])

In [141]:
A.T

array([[0, 2],
       [1, 3]])

In [142]:
C = np.full((3, 3), fill_value=2)

In [144]:
A + C

ValueError: operands could not be broadcast together with shapes (2,2) (3,3) 

### 向量和矩阵的运算

In [145]:
v = np.array([1,2])


In [146]:
A

array([[0, 1],
       [2, 3]])

In [148]:
v + A  # 一个向量和一个矩阵做加法，即每一行都加上向量

array([[1, 3],
       [3, 5]])

In [149]:
np.vstack([v] * A.shape[0])  

array([[1, 2],
       [1, 2]])

In [150]:
np.vstack([v] * A.shape[0]) + A   # 相当于A+v

array([[1, 3],
       [3, 5]])

In [151]:
np.tile(v, (2, 1))  # 在行上如何堆叠，在列上如何堆叠

array([[1, 2],
       [1, 2]])

In [152]:
np.tile(v, (2, 1)) + A

array([[1, 3],
       [3, 5]])

In [153]:
v

array([1, 2])

In [154]:
A

array([[0, 1],
       [2, 3]])

In [155]:
v * A  # 元素乘法，并自动将v堆叠成A的形状

array([[0, 2],
       [2, 6]])

In [156]:
v.dot(A)  # 矩阵乘法

array([4, 7])

In [157]:
A.dot(v)  # 一个矩阵和一个向量，可以直接进行点积（numpy自动将v转化为列向量或行向量）

array([2, 8])

### 矩阵的逆

In [158]:
A

array([[0, 1],
       [2, 3]])

In [160]:
invA = np.linalg.inv(A)
invA

array([[-1.5,  0.5],
       [ 1. ,  0. ]])

In [161]:
A.dot(invA)  # 对角矩阵

array([[1., 0.],
       [0., 1.]])

In [162]:
invA.dot(A)

array([[1., 0.],
       [0., 1.]])

In [164]:
X = np.arange(16).reshape((2, 8))
X

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [165]:
np.linalg.inv(X)

LinAlgError: Last 2 dimensions of the array must be square

In [166]:
pinvX = np.linalg.pinv(X)  # 非方阵可以求伪逆矩阵
pinvX

array([[-1.35416667e-01,  5.20833333e-02],
       [-1.01190476e-01,  4.16666667e-02],
       [-6.69642857e-02,  3.12500000e-02],
       [-3.27380952e-02,  2.08333333e-02],
       [ 1.48809524e-03,  1.04166667e-02],
       [ 3.57142857e-02, -7.30583920e-18],
       [ 6.99404762e-02, -1.04166667e-02],
       [ 1.04166667e-01, -2.08333333e-02]])

In [168]:
pinvX.shape

(8, 2)

In [169]:
X.dot(pinvX)

array([[ 1.00000000e+00, -2.77555756e-16],
       [ 1.69309011e-15,  1.00000000e+00]])