In [1]:
import numpy as np
from sklearn import datasets
import matplotlib.pyplot as plt

boston = datasets.load_boston()

X = boston.data
y = boston.target

X = X[y < 50.0]
y = y[y < 50.0]

In [5]:
X.shape

(490, 13)

In [6]:
from my_ml.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_ratio=0.2, seed=666)

In [7]:
from my_ml.LinearRegression import LinearRegression
lg = LinearRegression()
lg.fit_normal(X_train, y_train)

Linearegression()

In [8]:
lg._theta

array([ 3.41173997e+01, -1.20354261e-01,  3.64423279e-02, -3.61493155e-02,
        5.12978140e-02, -1.15775825e+01,  3.42740062e+00, -2.32311760e-02,
       -1.19487594e+00,  2.60101728e-01, -1.40219119e-02, -8.35430488e-01,
        7.80472852e-03, -3.80923751e-01])

In [9]:
lg.coefficient_

array([-1.20354261e-01,  3.64423279e-02, -3.61493155e-02,  5.12978140e-02,
       -1.15775825e+01,  3.42740062e+00, -2.32311760e-02, -1.19487594e+00,
        2.60101728e-01, -1.40219119e-02, -8.35430488e-01,  7.80472852e-03,
       -3.80923751e-01])

In [10]:
lg.interception_

34.117399723205686

In [11]:
lg.score(X_test, y_test)

0.8129794056212857

# scikit-learn的多元线性回归

In [12]:
from sklearn.linear_model import LinearRegression

In [13]:
lin_reg = LinearRegression()

In [14]:
lin_reg.fit(X_train, y_train)

LinearRegression()

In [16]:
lg.interception_

34.117399723205686

In [17]:
lg.coefficient_

array([-1.20354261e-01,  3.64423279e-02, -3.61493155e-02,  5.12978140e-02,
       -1.15775825e+01,  3.42740062e+00, -2.32311760e-02, -1.19487594e+00,
        2.60101728e-01, -1.40219119e-02, -8.35430488e-01,  7.80472852e-03,
       -3.80923751e-01])

In [15]:
lg.score(X_test, y_test)

0.8129794056212857

# KNN regressor

In [18]:
from sklearn.neighbors import KNeighborsRegressor

In [22]:
knn_reg = KNeighborsRegressor()
knn_reg.fit(X_train, y_train)
knn_reg.score(X_test, y_test)

0.5865412198300899

In [23]:
from sklearn.model_selection import GridSearchCV

In [24]:
param_grid = [
    {
        "weights":["uniform"],
        "n_neighbors":[i for i in range(1, 11)]
    },
    {
        "weights":["distance"],
        "n_neighbors":[i for i in range(1, 11)],
        "p":[i for i in range(1, 6)]
    }
]

In [25]:
gridsearchcv = GridSearchCV(knn_reg, param_grid, n_jobs=-1, verbose=1)  #-1是用所有的核,verbose输出的内容
gridsearchcv.fit(X_train, y_train)

Fitting 5 folds for each of 60 candidates, totalling 300 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 32 concurrent workers.
[Parallel(n_jobs=-1)]: Done 136 tasks      | elapsed:    1.7s
[Parallel(n_jobs=-1)]: Done 300 out of 300 | elapsed:    1.8s finished


GridSearchCV(estimator=KNeighborsRegressor(), n_jobs=-1,
             param_grid=[{'n_neighbors': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
                          'weights': ['uniform']},
                         {'n_neighbors': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
                          'p': [1, 2, 3, 4, 5], 'weights': ['distance']}],
             verbose=1)

In [26]:
gridsearchcv.best_estimator_

KNeighborsRegressor(n_neighbors=7, p=1, weights='distance')

In [27]:
gridsearchcv.best_score_    # 交叉验证

0.652216494152461

In [28]:
gridsearchcv.best_estimator_.score(X_test, y_test)

0.7160666820548707

# 关于线性回归模型的可解释性

In [29]:
import numpy as np
from sklearn import datasets
import matplotlib.pyplot as plt

boston = datasets.load_boston()

X = boston.data
y = boston.target

X = X[y < 50.0]
y = y[y < 50.0]

In [30]:
from sklearn.linear_model import LinearRegression
lin_reg = LinearRegression()
lin_reg.fit(X_train, y_train)

LinearRegression()

In [31]:
lin_reg.coef_

array([-1.20354261e-01,  3.64423279e-02, -3.61493155e-02,  5.12978140e-02,
       -1.15775825e+01,  3.42740062e+00, -2.32311760e-02, -1.19487594e+00,
        2.60101728e-01, -1.40219119e-02, -8.35430488e-01,  7.80472852e-03,
       -3.80923751e-01])

In [32]:
# 系数的绝对值的大小决定了特征的重要性高低.  负数表示负相关，正数表示正相关
np.argsort(lin_reg.coef_)

array([ 4,  7, 10, 12,  0,  2,  6,  9, 11,  1,  3,  8,  5])

In [33]:
boston.feature_names[np.argsort(lin_reg.coef_)]

array(['NOX', 'DIS', 'PTRATIO', 'LSTAT', 'CRIM', 'INDUS', 'AGE', 'TAX',
       'B', 'ZN', 'CHAS', 'RAD', 'RM'], dtype='<U7')

In [35]:
print(boston.DESCR)

.. _boston_dataset:

Boston house prices dataset
---------------------------

**Data Set Characteristics:**  

    :Number of Instances: 506 

    :Number of Attributes: 13 numeric/categorical predictive. Median Value (attribute 14) is usually the target.

    :Attribute Information (in order):
        - CRIM     per capita crime rate by town
        - ZN       proportion of residential land zoned for lots over 25,000 sq.ft.
        - INDUS    proportion of non-retail business acres per town
        - CHAS     Charles River dummy variable (= 1 if tract bounds river; 0 otherwise)
        - NOX      nitric oxides concentration (parts per 10 million)
        - RM       average number of rooms per dwelling
        - AGE      proportion of owner-occupied units built prior to 1940
        - DIS      weighted distances to five Boston employment centres
        - RAD      index of accessibility to radial highways
        - TAX      full-value property-tax rate per $10,000
        - PTRATIO  pu